import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Slider.module.css'
import Slider from '../components/Slider'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza ButterCrust</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider/>

       HomePage
 
    </div>
  )
}
