import Head from 'next/head'
import Image from 'next/image'
import Slider from '../components/Slider'
import PizzaList from '../components/PizzaList'
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pizza ButterCrust</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider/>
      <PizzaList/>
 
    </div>
  )
}
